# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8b9a3c5574d4882222d7451ae29c3679bb97ca372e9677a114e8c3cba523d745a5990685fcf9484a2c90e3e04ee2ac5916c95c2fea44820bb44e6c8ec578637

test:
  secret_key_base: f3a68dd788a618071fdeb1e6dc096397cef46e4252c112ef6974fbe1ba64d2bf5b6c8c0ce2d77c2509ac9317ddee13f333219c7b1703084ff82f5786cc72becf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
